### PR TITLE
cross-compatibility with JUJU ADAMS - INPUT

### PR DESCRIPTION
**Pull request by Anapsys**
Changes to allow rt-shell to play along with the newest release of **Input**: https://github.com/JujuAdams/input which overrides the functionality of **keyboard_string**. This feature can be toggled by use of the macro. 

+ updates project to latest GMKS version
+ adds configuration macro script
+ adds compatibility functions for keyboard_string accessor/mutator
~ replaces all instances of direct keyboard_string access

### CODE REVIEW

**Comment by offalynne** [comment]
Thank you so much for authoring this compatibility fix, we've addressed the problem on Input's end so this should no longer be requisite. <3

https://github.com/JujuAdams/Input/pull/168/commits/ec4497f0478196f1a1aed6465ff9ac5d6b71d7bb

**Comment by nickavv** [comment]
Hi, sorry for not noticing this PR earlier, I never got a notification from GitHub. Personally, I'd consider this to be an out-of-scope change to implement into rt-shell. Fundamentally, I don't like the idea of having code in the repo that relies on other libraries, even if it is behind a macro. This seems like a good candidate for a fork, potentially?

**Comment by offalynne** [comment]
We’re slicing the text-entry stuff out of the Input library anyway as standalone — thanks & sorry for the trouble @Anapsys !

**Comment by nickavv** [comment]
Thanks for the update @offalynne!
I'll close this MR then, @Anapsys if there's still something you think would be a good addition to rt-shell going forward we can discuss that, and thanks for the intended contribution!

**Pull request closed without merging**
